# Number of times to repeat this experiment
- repeat: 1
  data:
    # Dataset name
    name: chengdu
    meta:
      # Type of trajectory data to use
      - type: traj2vectime-trip
  
  models:
    # Transformer encoder for trajectory embedding
    - name: traj2vec_encoder
      config:
        # Base dimension for transformer model
        d_model: 64
        # Output embedding dimension
        output_size: 64
        hidden_size: 64
        num_layers: 2

      # Preprocessor for trajectory data
      preprocessor:
        # Type of preprocessor to use
        name: Trajectory2VecSampler

    # Decoder for trajectory reconstruction
    - name: traj2vec_decoder
      config:
        # Input embedding dimension from encoder
        encode_size: 64
        d_model: 64
        hidden_size: 128
        num_layers: 2

  pretrain:
    # Whether to load pre-trained weights
    load: false
    loss:
      # Autoregressive loss for trajectory reconstruction
      name: trajectory2vec
    trainer:
      # Generative pre-training approach
      name: generative
      config:
        num_epoch: 5
        batch_size: 16
        lr: 1.0e-3
        # Indices for encoder/decoder meta features
        enc_meta_i: [0]
        rec_meta_i: [0]
  
  downstream:
    # Destination prediction task
    - task: destination
      # Use first model (encoder) for prediction
      select_models: [0]
      # Use test set for evaluation
      eval_set: 2
      config:
        # Number of points to use for prediction
        pre_length: 1
        # Whether to fine-tune pre-trained model
        finetune: true
        num_epoch: 20
        batch_size: 16
        save_prediction: false
        lr: 1.0e-3
        # Early stopping patience
        es_epoch: 10
        meta_types:
          - traj2vectime-trip
        # Meta feature indices for encoder and labels
        enc_meta_i: [0]
        label_meta_i: [0]