- repeat: 1
  data:
    name: cd23_small
  models:
    - name: trajsim_encoder
      config:
        d_model: 32
        hidden_size: 32
        num_layers: 3
        dropout: 0.2
        bidirectional: true
        grid_col: 1
    - name: trajsim_decoder
      config:
        d_model: 32
        hidden_size: 32
        num_layers: 3
        dropout: 0.2
        grid_col: 1
    - name: trajsim_embedding
      config:
        meta_type: trajsim-0.001-300-2
        d_model: 32
        PAD: 0
  pretrain:
    load: false
    loss:
      name: trajsim
      config:
        criterion_name: KLDIV
        dist_decay_speed: 0.8
        timeWeight: 0.2
        use_discriminative: true
        discriminative_w: 0.5
        dis_freq: 10
        generator_batch: 256
    trainer:
      name: generativeiteration
      config:
        num_epoch: 15
        batch_size: 64
        lr: 1.0e-3
        meta_types:
          - trajsim-0.001-300-2
        enc_meta_i: [0]
        rec_meta_i: [0]
        max_grad_norm: 5.0
  downstream:
    - task: destination
      select_models: [0]
      eval_set: 2
      config:
        finetune: false
        num_epoch: 2
        batch_size: 512
        save_prediction: false
        lr: 1.0e-3
        es_epoch: 10
        pre_length: 3
        meta_types:
          - resample-60 